### ISSUE TITLE
Unable to dismiss modal / dialog without actually making a snippet 

### ISSUE THREAD

**Issue by JFrackson** [Wikunia/brackets-slacksnippet#2]
I just downloaded and went to test without having selected any code to find out I was trapped in the modal! A simple cancel or "x" that dismisses the modal would help get around this. Thanks!

**Comment by Wikunia** [comment]
Just for the moment a esc should work. But thanks for the issue, I will work on that one.

**Comment by JFrackson** [comment]
Great. Thanks for the great extension!

**Comment by Wikunia** [comment]
Sorry for the late response and thanks for the issue!
